instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('timeline.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeline/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

urlpatterns = [
   path('', views.index, name="home"),
   path('register', views.register, name='register'),
   path('profile', views.profile, name='profile'),
   path('timeline/new', views.new_post, name='new_post'),
   path('profile/edit', views.edit_profile, name='edit_profile'),
   path('<user_name>', views.users, name='user_profile'),
   path('post/<int:image_id>', views.image_view, name='image_view'),
   path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
   path('logout/', views.logout_view, name='logout'),
   path('search/', views.search,name='search'),
   # method views
   path('follow/<user_name>', views.follow, name='follow'),
   path('like/<int:image_id>',views.like,name='like')
]

timeline/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):

   user = models.OneToOneField(User, on_delete=models.CASCADE)
   avatar = models.ImageField(upload_to='avatar/', default='default.jpg')
   bio = models.TextField(max_length=140, blank=True, default='')

   def __str__(self):
      return f'{self.user.username}'
   
class Image(models.Model):

   img = models.ImageField(upload_to='', height_field=None, width_field=None, max_length=None)
   caption = models.TextField(max_length=280)
   author = models.ForeignKey(Profile, on_delete=models.CASCADE)
   time_posted = models.DateField(auto_now=True)
   
   def __str__(self):
      return self.caption

   def save_image(self):
      self.save()

   def delete_image(self):
      self.delete()

   def update_caption(self,cpt):
      self.caption = cpt
      self.save()

class Like(models.Model):

   liked = models.ForeignKey(Image, on_delete=models.CASCADE)
   liked_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

   @classmethod
   def likes(cls,img,prfl):
      like = cls(liked=img,liked_by=prfl)
      return like.save()

   def delete_like(self):
      self.delete()

class Comments(models.Model):
   
   comment = models.CharField(max_length=140)
   comment_author = models.ForeignKey(Profile, on_delete=models.CASCADE)
   commented_on = models.ForeignKey(Image, on_delete=models.CASCADE)

   def __str__(self):
      return self.comment

class Followed(models.Model):

   followers = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='followed_by',null=True)

   def __str__(self):
      return self.followers
 
   @classmethod
   def follow(cls,prfl):
      follow = cls(followers=prfl)
      return follow.save()

class Follows(models.Model):

   following = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='following',null=True)

   def __str__(self):
      return self.following

   @classmethod
   def follow(cls,prfl):
      follow = cls(following=prfl)
      return follow.save()

timeline/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import Profile,Comments,Image

class Registration(UserCreationForm):
   '''
   Form that extends the UserCreationForm

   Added fields are the name and email fields.
   '''
   username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
   email= forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), max_length=64)
   password1= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
   password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))


   class Meta(UserCreationForm.Meta):
      model = User
      fields = UserCreationForm.Meta.fields + ("email","username","password1")
   

class ProfileUpdateForm(forms.ModelForm):
   '''
   Profile update form. 

   Allows user to add a bio and a custom avatar.
   '''

   class Meta:
      model = Profile
      fields = ['avatar','bio']
      widgets = {
         'bio': forms.Textarea(attrs={'placeholder': 'Bio'})         
      }

class UserUpdateForm(forms.ModelForm):
   '''
   User update form.

   A user can add their name
   '''
   first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
   last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
   class Meta:
      model = User
      fields = ['first_name','last_name']

class LoginForm(AuthenticationForm):
   '''
   Login form.

   Takes a username and password
   '''
   username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
   class Meta:
      model = User
      fields = ['username', 'password']


class CommentForm(forms.ModelForm):
   '''
   Comment form
   '''
   class Meta:
      model = Comments
      fields = ['comment']
      widgets = {
         'comment': forms.TextInput(attrs={'placeholder': 'Add a Comment'})        
      }

class ImageForm(forms.ModelForm):
   '''
   Image form
   '''
   class Meta:
      model = Image
      fields = ['img','caption']
      widgets = {
         'caption': forms.Textarea(attrs={'placeholder': 'Enter Your Caption'})         
      }

timeline/views.py
from django.shortcuts import render,redirect
from .models import Profile,Image,Comments,Followed,Follows,Like
from django.contrib.auth.models import User
from .forms import Registration,ProfileUpdateForm,UserUpdateForm,LoginForm,CommentForm,ImageForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import _EnsureCsrfCookie 

# Create your views here.
@login_required(login_url='register')
def index(request):
   user = request.user
   comments = Comments.objects.all()

   if request.method == 'POST':
      form = CommentForm(request.POST)
      if form.is_valid():
         image_id = request.POST["image_id"]
         comment = form.save(commit=False)
         comment.comment_author = user.profile
         comment.commented_on_id = int(image_id)
         comment.save()
         return redirect('home')
   else:
      form = CommentForm()

   images = Image.objects.order_by('-time_posted')

   context = {
      'images': images,
      'form': form,
      'user': user,
      'comments': comments
   }
   return render(request, 'timeline/timeline.html', context)

@login_required
def users(request,user_name):
   user = User.objects.filter(username=user_name).first()
   images = Image.objects.filter(author=user.profile)

   context = {
      'user': user,
      'images': images
   }

   return render(request, 'timeline/user.html', context)

@login_required
def new_post(request):
   user = request.user
   if request.method == 'POST':
      form = ImageForm(request.POST,request.FILES)
      if form.is_valid():
         image = form.save(commit=False)
         image.author = user.profile
         image.save()
         return redirect('home')
   else:
      form = ImageForm()


   context = {
      'form': form
   }

   return render(request, 'timeline/new-post.html', context)

def register(request):

   if request.method == 'POST':
      form = Registration(request.POST)
      if form.is_valid():
         form.save()
         username = form.cleaned_data.get('username')
         raw_password = form.cleaned_data.get('password1')
         user = authenticate(username=username, password=raw_password)
         login(request, user)
         user = User.objects.filter
         return redirect('edit_profile')
   else:
      form = Registration()

   context = {
      'form': form
   }

   return render(request, 'timeline/register.html', context)


@login_required
def profile(request):

   user = request.user
   images = Image.objects.filter(author=user.profile)

   context = {
      'user': user,
      'images': images
   }

   return render(request, 'timeline/profile.html', context)

@login_required
def edit_profile(request):

   user = request.user

   if request.method == 'POST':
      form = ProfileUpdateForm(request.POST,request.FILES,instance=user.profile)
      user_form = UserUpdateForm(request.POST,instance=user)
      if user_form.is_valid() and form.is_valid():
         user_form.save()
         profile = form.save(commit=False)
         profile.user = user
         profile.save()
         messages.info(request, 'You\'ve successfully updated your account!')
         return redirect('profile')
   else:
      form = ProfileUpdateForm(instance=request.user)
      user_form = UserUpdateForm(instance=request.user.profile)

   context = { 
      'user': user,
      'user_form': user_form,
      'form': form
   }

   return render(request, 'timeline/edit-profile.html', context)

@login_required
def search(request):

   if 'insta_search' in request.GET and request.GET["insta_search"]:
      searched = request.GET.get("insta_search")
      if searched:
         user = User.objects.filter(username=searched).first()

   context = {
      'searched': searched,
      'user': user
   }

   return render(request, 'timeline/search.html', context)


def login_view(request):
   if request.method == 'POST':
      form = LoginForm()
      if form.is_valid():
         username = form.cleaned_data.get('username')
         raw_password = form.cleaned_data.get('password1')
         user = authenticate(username=username, password=raw_password)
         login(request, user)
         return redirect('home')
   else:
      form = LoginForm()

   context = {
      'form': form
   }

   return render(request, 'registration/login.html', context)


@login_required
def logout_view(request):
   logout(request)
   return redirect('login')


@login_required
def image_view(request,image_id):

   user = request.user

   image = Image.objects.filter(pk=image_id).first()
   comments = Comments.objects.filter(commented_on=image)

   if request.method == 'POST':
      form = CommentForm(request.POST)
      if form.is_valid():
         image_id = request.POST["image_id"]
         comment = form.save(commit=False)
         comment.comment_author = user.profile
         comment.commented_on_id = int(image_id)
         comment.save()
         return redirect('home')
   else:
      form = CommentForm()

   context = {
      'image': image,
      'comments': comments,
      'form': form
   }

   return render(request,'timeline/image_view.html',context)


def like(request,image_id):

   user = request.user

   image = Image.objects.filter(pk=image_id).first()
   like = image.like_set.filter(liked_by=user.profile).first()
   # like = Like.objects.get(liked=image,liked_by=user.profile)

   if like:
      like.delete()
   else:
      Like.likes(image,user.profile)

   return redirect('home')

def follow(request,user_name):

   user = request.user
   follows = Follows.objects.filter(profile=user.profile)
   followed_user = User.objects.filter(username=user_name).first()
   if user.profile not in follows:
      Follows.follow(user.profile)
      Followed.follow()
      return redirect('profile')
   else:
      Follows.objects.get(following=user.profile).delete()
      return redirect('profile')

timeline/templates/timeline/edit-profile.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   {% include "timeline/nav.html" %}

   <div class="page">
      
      <div class="update-form">

         <form action="" method="post" enctype="multipart/form-data">
            <div class="legend">
               <h5>Edit Profile</h5>
            </div>
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ form.as_p }}
            <button type="submit" class="btn">Submit</button>
         </form>
      </div>
      
   </div>

{% endblock content %}

timeline/templates/timeline/image_view.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}
  

   {% include "timeline/nav.html" %}

   <div class="page"></div>
   
   <div class="image-view">
      <div class="post-image">
         <img src="{{ image.img.url }}" alt="">
      </div>
      <div class="image-details">
         <div class="image-author">
            <div class="avatar-sm">
               <img src="{{ image.author.avatar.url }}" alt="">
            </div>
            <p>{{ image.author.user.username }}</p>
            
         </div>
         <div class="image-content">
            <p><span>{{ image.author.user.username }}</span>{{ image.caption }}</p>
            <div class="post-comments">
                  
               {% for comment in comments  %}
                  <p><span>{{ comment.comment_author.user.username }}</span> {{ comment.comment }}</p>
               {% endfor %}                    
               
            </div>
         </div>
         <div class="post-icons">   
            <a href="{% url 'like' image.id %}">
               <img src="{% static 'images/like.svg' %}" alt="">
            </a>
         </div>
         <div class="post-likes">
            <p>{{ image.like_set.count }} Likes</p>
         </div>
         <div class="post-comment-field">
            <form action="" method="POST">
               {% csrf_token %}
               {{ form.as_p }}
               <input type="text" name="image_id" id="image_id" value="{{ post.id }}" hidden>
               <button type="submit" hidden></button>
            </form>
         </div>
      </div>
   </div>


{% endblock content %}

timeline/templates/timeline/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700" rel="stylesheet">
   <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
   <title>Instagram</title>
</head>
<body>
   
   {% block content %}
     
   {% endblock content %}

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

timeline/templates/timeline/nav.html
{% load static %}
<div class="nav-bg">
   <nav>
      <div class="logo">
         <div class="logo-icon">
            <a href="{% url 'home' %}">
               <img src="{% static 'images/insta_icon.svg' %}" alt="">
            </a>
            </div>
         <div class="glyph">
            <a href="{% url 'home' %}">
               <img src="{% static 'images/insta_text.svg' %}" alt="">
            </a>
         </div>
      </div>

      <div class="search">
         <form action="{% url 'search' %}" method="get">
            <input type="text" name="insta_search" id="insta-search" placeholder="&#xf002; Search">
            <button type="submit" hidden></button>
         </form>
      </div>
      <div class="user-menu">
         <div class="profile-icon">
            <a href="{% url 'profile' %}">
               <img src="{% static 'images/account.svg' %}" alt="">
            </a>
         </div>
      </div>
   </nav>
</div>

timeline/templates/timeline/new-post.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   {% include "timeline/nav.html" %}

   <div class="page">
      
      <div class="update-form">

         <form action="" method="post" enctype="multipart/form-data">
            <div class="legend">
               <h5>New Post</h5>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Create Post</button>
         </form>
      </div>
      
   </div>

{% endblock content %}

timeline/templates/timeline/profile.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   {% include "timeline/nav.html" %}

   <div class="page"></div>
      <div class="container">

         <div class="profile-content">

            <div class="main-avatar">
               <img src="{{ user.profile.avatar.url }}" alt="">
            </div>
            <div class="profile-details">
               <div class="profile-top">
                  <div class="profile-user">
                     <h1>{{ user.username }}</h1>
                  </div>
                  <div class="edit-btn">
                     <a href="{% url 'edit_profile' %}">Edit Profile</a>
                     <button id="settings"><i class="fas fa-cog"></i></button> 
                  </div>
                  
               </div>


               <div class="activity-count">
                  <p><span>{{ user.profile.image_set.count }}</span> posts </p>
                  <p><span>{{ user.profile.followed_by.count }}</span> followers </p>
                  <p><span>{{ user.profile.following.count }}</span> following </p>
               </div>
               {% if user.profile.bio %}
                  <div class="bio">
                     <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                     <p>{{ user.profile.bio }}</p>
                  </div>
               {% endif %}
            </div>
            
         </div>

      </div>


      <div class="profile-images">
         {% for image in images %}
         <a href="{% url 'image_view' image.id %}"></a>
            <div class="image-card">
               <img src="{{ image.img.url }}" alt="">
            </div>
         </a>

         {% endfor %}
      </div>

   

   <div class="modal">
      <div class="settings-list">
         <div class="text">
            <a href="{% url 'edit_profile' %}">
               <p>Edit Profile</p>
            </a>
            <a href="{% url 'logout' %}">
               <p class="with-border">Log Out</p>
            </a>
            <p id="cancel">Cancel</p>
         </div>

      </div>
   </div>

{% endblock content %}

timeline/templates/timeline/register.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   <div class="page">
      
      <div class="form-container">

         <form action="" method="post">
            <div class="legend">
               <div class="form-glyph">
                  <img src="{% static 'images/insta_text.svg' %}" alt="">
               </div>
               <h5>Sign up to see photos from your friends</h5>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Sign Up</button>
         </form>
         
      </div>
      
      <div class="acc-status-check">
         <p>Have an account? <a href="{% url 'login' %}">Log In</a></p>
      </div>
      
   </div>
  
{% endblock content %}

timeline/templates/timeline/search.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}
  
   {% include "timeline/nav.html" %}

   <div class="page"></div>
   <div class="container">
      {% if user %}
        <h5 class="search-result">Your search for <span>{{ searched }}</span> returned:</h5>
         <a href="{% url 'user_profile' user.username %}">
            <div class='user-card'>
               <div class="avatar-md">
                  <img src="{{ user.profile.avatar.url }}" alt="">
               </div>
               <div class='user-details'>
                  <p>{{ user.username }}</p>
               </div>
            </div>
         </a>
      {% else %}
        <h5 class='not-found'>There's no user going by that username</h5>
      {% endif %}
      
   </div>

{% endblock content %}

timeline/templates/timeline/timeline.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   {% include "timeline/nav.html" %}

   <div class="page"></div>

   <div class="tl-container">
      <div class="posts-container">

         {% for post in images %}
            <div class="post-card">
               <div class="post-top">
                  <div class="avatar-sm">
                     <img src="{{ post.author.avatar.url }}" alt="">
                  </div>
                  <a href="{% url 'user_profile' post.author.user.username %}"><p>{{ post.author.user.username }}</p></a>
               </div>
               <div class="post-image">
                  <a href="{% url 'image_view' post.id %}">
                     <img src="{{ post.img.url }}" alt="">
                  </a>
                  
               </div>
               <div class="post-icons">   
                  <a href="{% url 'like' post.id %}">
                     <img src="{% static 'images/like.svg' %}" alt="">
                  </a>
               </div>
               <div class="post-likes">
                  <p>{{ post.like_set.count }} Likes</p>
               </div>
               <div class="post-caption">
                  <p><span>{{ post.author.user.username }}</span>{{ post.caption }}</p>
               </div>
               <div class="post-comments">
                  
                  {% for comment in comments  %}
                     {% if comment.commented_on == post %}
                        <p><span>{{ comment.comment_author.user.username }}</span> {{ comment.comment }}</p>
                     {% endif %}
                  {% endfor %}                    
                  
               </div>
               <div class="post-comment-field">
                  <form action="" method="POST">
                     {% csrf_token %}
                     {{ form.as_p }}
                     <input type="text" name="image_id" id="image_id" value="{{ post.id }}" hidden>
                     <button type="submit" hidden></button>
                  </form>
               </div>
            </div>
         {% endfor %}

      </div>
      <div class="sidebar">
         <a href="{% url 'profile' %}">
            <div class="current-user">
                  <div class="avatar-md">
                     <img src="{{ user.profile.avatar.url }}" alt="{{ user.first_name }}Avatar">
                  </div>
                  <div class='name'>
                     <h4>{{ user.username }}</h4>
                     <p>{{ user.first_name }} {{ user.last_name }}</p>
                  </div>
            </div>
         </a>
         <div class="post-btn">
            <a href="{% url 'new_post' %}">
               <button id="newpost"> + Add Post</button>
            </a>
         </div>
      </div>

   </div>

   <div class="modal">
      <div class="new-post">
         <div class="form-container">
            <form action="" method="post" enctype="multipart/form-data">
               <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" >
               {{ new_post.as_p }}
               <button type="submit">Post</button>
            </form>
         </div>
      </div>
   </div>
{% endblock content %}

timeline/templates/timeline/user.html
{% extends "timeline/layout.html" %}
{% load static %}

{% block content %}

   {% include "timeline/nav.html" %}


   
   <div class="page"></div>
      <div class="container">

         <div class="profile-content">

            <div class="main-avatar">
               <img src="{{ user.profile.avatar.url }}" alt="">
            </div>
            <div class="profile-details">
               <div class="profile-top">
                  <div class="profile-user">
                     <h1>{{ user.username }}</h1>
                  </div>
                  <div class="edit-btn">
                     <a href="{% url 'follow' user.username %}">Follow</a>
                  </div>
               </div>


               <div class="activity-count">
                  <p><span>{{ user.profile.image_set.count }}</span> posts </p>
                  <p><span>{{ user.profile.followed_by.count }}</span> followers </p>
                  <p><span>{{ user.profile.following.count }}</span> following </p>
               </div>
               {% if user.profile.bio %}
                  <div class="bio">
                     <p>{{ user.profile.bio }}</p>
                  </div>
               {% endif %}
            </div>
            
         </div>

      </div>


      <div class="profile-images">
         {% for image in images %}
         
         <div class="image-card">
            <a href="{% url 'image_view' image.id %}">
               <img src="{{ image.img.url }}" alt="">
            </a>
         </div>
         
         {% endfor %}
      </div>

{% endblock content %}